### PR TITLE
Issue 79

### PR DESCRIPTION
**Pull request by jphager2**
In view collection, provide a null view if views are empty.

Currently breaks pakyow-ui.

### CODE REVIEW

**Comment by bryanp** [comment]
Just FYI I am still thinking this over and what we want to do here. This presents an interesting option that I hadn't considered before now. Give me a couple more days :-)

**Comment by bryanp** [comment]
Finally finished thinking about this. I think for now we should just make `ViewCollection#match` a no-op if `@views.empty?`. That seems consistent with other behavior in that transforming an empty collection doesn't cause failures. It's likely something we should report to the user (at a minimum with logging, or perhaps raising an exception) but that's something I'd like to address separately.

**Comment by jphager2** [comment]
I would say that makes a lot of sense. For me exception is preferable,
especially sense otherwise you will get one down the line, and then you
would have to go back and track it down in the log.

**Comment by bryanp** [comment]
Yep, I tend to agree with you on exceptions vs log. I'll go ahead and make the change, then create an issue to raise exceptions when attempting to transform an empty `ViewCollection` (we won't hold up 0.10 for this).

**Pull request closed without merging**
