### PR TITLE
WIP: Make current environment more consistent

### PR DESCRIPTION
**Pull request by karimmtarek**
This is a WIP to tackel #128.

### CODE REVIEW

**Comment by bryanp** [comment]
Looks nice, but the specs are failing

**Comment by karimmtarek** [comment]
Yep, I'll fix that and push it back.

**Comment by karimmtarek** [comment]
@bryanp I added `to_s` to the `environment` argument value, to pass the test; though I'm not sure if that's the best way to go about it, what do you think?

**Comment by bryanp** [comment]
This might be better:

```ruby
def initialize(environment: ENV['RACK_ENV'])
  environment = :development if environment.nil? || environment.empty?
  ENV['RACK_ENV'] = environment
end
```

**Comment by karimmtarek** [comment]
The problem I had with the previous code (before adding the `to_s`) is that when the `ENV['RACK_ENV']` is not set, and the `:development` value gets assigned to it, we get this error 
```
`[]=': no implicit conversion of Symbol into String
```
Even with the code you posted this didn't change.

One thing I'm curious about(learning curiosity) is why is adding this line:
```ruby
environment = :development if environment.nil? || environment.empty?
```
Might be better that just using `to_s`

So, what do you think?

**Comment by bryanp** [comment]
Using `to_s` would convert `nil` to `""` and a `Symbol` to a `String`.

Can you provide the entire backtrace for the error?

**Comment by karimmtarek** [comment]
Thanks for the explanation.
Here is the backtrace:
```
+/Users/karim/code/projects/pakyow/pakyow/lib/pakyow/commands/console.rb:8:in `[]=': no implicit conversion of Symbol into String (TypeError)
       +	from /Users/karim/code/projects/pakyow/pakyow/lib/pakyow/commands/console.rb:8:in `initialize'
       +	from /Users/karim/code/projects/pakyow/pakyow/lib/pakyow/command_line_interface.rb:36:in `new'
       +	from /Users/karim/code/projects/pakyow/pakyow/lib/pakyow/command_line_interface.rb:36:in `console'
       +	from /Users/karim/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
       +	from /Users/karim/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
       +	from /Users/karim/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
       +	from /Users/karim/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
       +	from bin/pakyow:4:in `<main>'
```

I pushed the latest changes so you can have a look and advise if I missed something up.

**Comment by jphager2** [comment]
Hey, this is kind of news to me, but apparently ENV only allows values that can be coerced into a `String`.

Check out the implementation of `ENV#[]=`
http://ruby-doc.org/core-2.1.4/ENV.html

Here is the relevant part of the code (`nm` is the name and `val` is the value):

```
    SafeStringValue(nm);
    SafeStringValue(val); 
    name = RSTRING_PTR(nm);
    value = RSTRING_PTR(val);
    if (memchr(name, '\0', RSTRING_LEN(nm)))
        rb_raise(rb_eArgError, "bad environment variable name");
    if (memchr(value, '\0', RSTRING_LEN(val)))
        rb_raise(rb_eArgError, "bad environment variable value");
```

So looks like you are going to have to:

```
ENV['RACK_ENV'] = environment.to_s

#and if you always want to get a string out of 'RACK_ENV;
ENV['RACK_ENV'].to_sym # unless ENV['RACK_ENV'].nil?
```

**Comment by bryanp** [comment]
Interesting findings, @jphager2!

**Comment by karimmtarek** [comment]
@bryanp what do you think? should I revert back to using `to_s` as @jphager2 is suggesting?

**Comment by bryanp** [comment]
Yeah, we can't avoid it here.

**Comment by karimmtarek** [comment]
Done :+1:

**Comment by bryanp** [comment]
Nice! Merging 😀

**Pull request merged**
