### PR TITLE
Use thor as generator

### PR DESCRIPTION
**Pull request by yodarunamok**
Initial attempt to get this working.

### CODE REVIEW

**Comment by yodarunamok** [comment]
So @bryanp, I've been working on this a fair bit, and I keep on getting the same error:
```
bundler: failed to load command: ./commands/pakyow (./commands/pakyow)
NoMethodError: undefined method `last' for nil:NilClass
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:101:in `destination_root'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:134:in `find_in_source_paths'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:59:in `initialize'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:52:in `new'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/directory.rb:52:in `directory'
  /Users/chris/Clients/Metabahn/pakyow/pakyow/lib/generators/pakyow/app/app_generator.rb:40:in `build'
  /Users/chris/Clients/Metabahn/pakyow/pakyow/lib/generators/pakyow/app/app_generator.rb:15:in `start'
  /Users/chris/Clients/Metabahn/pakyow/pakyow/lib/pakyow/cli.rb:17:in `new'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /Users/chris/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Users/chris/Clients/Metabahn/pakyow/pakyow/commands/pakyow:5:in `<top (required)>'
```
I've tried all sorts of method to ensure that `@destination_stack` isn't `nil`, including setting it [here](https://github.com/pakyow/pakyow/pull/252/files#diff-184774305996c15c873336a370e129d0R29). At least it seems what that should do. I've also tried passing in the data as a config option. Not sure what's going on...

**Comment by bryanp** [comment]
It looks like you're setting `@destination_root`, not `@destination_stack`.

**Comment by yodarunamok** [comment]
Well, here's the relevant method from Thor:
```ruby
# Sets the root for this thor class. Relatives path are added to the
# directory where the script was invoked and expanded.
#
def destination_root=(root)
  @destination_stack ||= []
  @destination_stack[0] = File.expand_path(root || "")
end
```

**Comment by yodarunamok** [comment]
Moving right along... I'm getting this warning right now:

`[WARNING] Attempted to create command "build" without usage or description. Call desc if you want this method to be available as command or declare it inside a no_commands{} block.`

I'm assuming that we don't want "build" to be a command, as it's really just doing the work for another command; am I correct?

**Comment by bryanp** [comment]
Correct, we'll invoke `build` from the CLI (since it should be tied to the `new` command).

**Comment by yodarunamok** [comment]
This should be all ready to go. I did a comparison of the output using Thor with the old way using my favorite tool for such things (BBEdit) and everything checks out.

**Comment by bryanp** [comment]
I just pushed some changes. When I pulled it down it was spitting out the entire path to the files it was creating, starting at the root of my filesystem. Turns out it was doing that because `destination_root` was being set to `/`, but it should be `./`.

I then started digging into the docs a bit more, because it seemed odd to me that we'd even need to set that at all. Ended up refactoring this to use `Thor::Group` and an action for `bundle install`. This resulted in removing nearly all of our generation code.

Take a look and let me know what you think.

**Comment by yodarunamok** [comment]
Looks fine to me. Much of what I originally did felt less-than-optimal to me, and I felt I wasn't getting Thor completely, as I had to do a lot of looking at the code thereof, as the documentation wasn't always 100% helpful. The bits I'm proudest of are that teeny `dot` method and the other tweaks to get Thor to do its thing.

One thing I'm not clear on, is the `create_project` method called automagically by Thor at some point so it can do its thing? I'm having a hard time figuring out where it's called.

**Comment by bryanp** [comment]
Yep, every public method in `Thor::Group` is called automatically, in order.

Thanks for your work on this. You got us pointed in the right direction.

**Pull request merged**
