### PR TITLE
Fix load path concerns

### PR DESCRIPTION
**Pull request by iamvery**
Two major things happening here

1. make sure all lib code is namespace to `./lib/pakyow/`
1. make sure all constants defined by lib code are namespaced to the `Pakyow` module.

Obviously this touches _a lot_, so I need some accountability beyond the test suite.

cc @bryanp

### CODE REVIEW

**Comment by iamvery** [comment]
To keep the changeset to a minimum, I opted to punt on consistency in the gems. For e.g. the realtime lib namespaces things to `./lib/pakyow-realtime/`. This is Good Enough™, but for consistency I'd probably move everything under `./lib/pakyow/` maybe `./lib/pakyow/realtime/` for this particular case. New issue?

**Comment by iamvery** [comment]
First time I ran the tests locally, I got a failure in pakyow-presenter. That might indicate an order dependency somewhere in the suite. So far I haven't been able to reproduce. https://gist.github.com/iamvery/fb6c9b4325a21ed628ea

**Comment by bryanp** [comment]
Looking good. I'll run a few Pakyow apps from this branch before merging just to be sure.

Here's what I'd ultimately like to see across all libs (explained in terms of pakyow-core):

1. `lib/pakyow-core` only requires `pakyow/core`
2. `pakyow/core` requires everything else (essentially what `pakyow/core/base.rb` does now)

You mentioned this in your comment so I know you're aware; just restating to be clear :-)

I am okay doing the rest of the work as part of this PR since we're already touching most everything.

Oh, and you can disregard that test failure. It's due to a brittle test that doesn't reset state when there's a failure. I need to take the time to fix that up, but haven't done that yet.

**Comment by iamvery** [comment]
Just pushed an update to fix merge conflict. I think I'll leave those other organization changes to another PR. At least this _should_ address the conflicting loadpath concerns. Legit?

**Comment by bryanp** [comment]
Awesome, just merged manually. Thanks for your work on this! Just so I know how to plan, do you think you'll tackle the other PR in the next couple days? If not I'll jump on it so we can get 0.11 out the door 😁

**Comment by iamvery** [comment]
You mean reorganizing the files under `pak/core` and such? I probably won't have a lot of time in the next couple days. Have your way with it! :smile_cat:

**Pull request merged**
