### PR TITLE
Server help fixes redux

### PR DESCRIPTION
**Pull request by yodarunamok**
Okay, this PR is a mulligan of [a previous one](https://github.com/pakyow/pakyow/pull/218). It addresses issue #217.

@bryanp: The main thing that I'm wondering at this point is how to test things to make sure that my fixes didn't break anything. If I attempt to just run Pakyow server I get this error: "You must run the \`pakyow server\` command in the root directory of a Pakyow project."

### CODE REVIEW

**Comment by bryanp** [comment]
@yodarunamok try running `bundle exec pakyow` to see the gem version.

**Comment by yodarunamok** [comment]
@bryanp okay, just ran `bundle exec pakyow v` and got the response:
```
Pakyow v1.0.0-alpha
```
I'm more wondering about testing though... Do I just need to create a basic pakyow project to use for testing this, or is there a better way to test things when actually working on Pakyow?

**Comment by bryanp** [comment]
There's a bundled example app at `example`. From there, run `bundle exec pakyow` to run it through all the commands.

**Comment by yodarunamok** [comment]
aha! thanks!

**Comment by yodarunamok** [comment]
okay, this should be ready to go...

**Pull request merged**
