### PR TITLE
[WIP] Ensure that class attribute values are arrays

### LINKED ISSUE #177: Ensure that class attribute values are arrays
Pakyow currently lets you do this:

``` ruby
view.attrs.class = 'foo'
```

This can cause problems down the line (e.g. https://github.com/pakyow/ring/pull/8) because the class attribute is expected to be an array of values. We should still allow this, but should make sure it's an array before replacing the current value.

### PR DESCRIPTION
**Pull request by karimmtarek**
Closes #177 

@bryanp this is just to start the conversation.
This new line will make sure whatever the value is it will be converted to an Array. Does that fulfill the requirements? or there is more to it than that?

### CODE REVIEW

**Comment by bryanp** [comment]
There's a lot more to this, unfortunately. If you look at presenter's `Attr` class it handles four types of attributes: Boolean (e.g. checked), Multiple (e.g. class), Hash (e.g. style), as well as normal string value attributes (e.g. action). We do a lot of validation when setting these on `View`. All of this logic needs to be present for `UIAttrs` as well. Essentially: https://github.com/pakyow/pakyow/blob/master/pakyow-presenter/lib/pakyow/presenter/attributes.rb

**Comment by karimmtarek** [comment]
Do we have specs already in place that I can code against?

**Comment by bryanp** [comment]
See if this helps: https://github.com/pakyow/pakyow/blob/master/pakyow-presenter/spec/integration/support/mixins/attr_specs.rb

**Comment by karimmtarek** [comment]
I'm closing this, I don't think I understand the problem to be able to write something and I don't feel comfortable copy code blindly from that other file. Sorry :(

**Comment by bryanp** [comment]
No worries :)

**Pull request closed without merging**
