### PR TITLE
Initial rework of Documentation Style Guide.  Moved parts of the docu…

### PR DESCRIPTION
**Pull request by yodarunamok**
…mentation around.  Added a contribution section.

### CODE REVIEW

**Comment by bryanp** [comment]
Nice contribution! I really like everything here. Using blockquotes to denote beginner (or maybe even advanced content) will really help make the docs more clear. However, the way they're implemented leaves us with very few styling options. Ideally we could define a "type" and define the style for that type (including the image) in an external stylesheet.

Kramdown supports [Attribute List Definitions](http://kramdown.gettalong.org/syntax.html#attribute-list-definitions) which would work (in fact, they use this in their [syntax guide](https://github.com/gettalong/kramdown/blob/master/doc/syntax.page#L1653)). But defining class names in Markdown feels wrong. IMO it would be better to define the type of blockquote without tying it directly to a class name.

pakyow-markdown uses [Redcarpet](https://github.com/vmg/redcarpet), which has a way to [define custom renderers](https://github.com/vmg/redcarpet#and-you-can-even-cook-your-own). We could create a renderer with a custom `block_quote` method that did what we wanted.

Here's a possible syntax for defining types of blockquotes:

```
>(footype) foo
```

It would be rendered like:

```html
<blockquote class="bq-footype">
  foo
</blockquote>
```

What do you think?

**Comment by yodarunamok** [comment]
Redcarpet sounds like an interesting idea.  That said, with distinct images it's possible to have an unlimited number of blockquote types using CSS identifiers like this:
`blockquote > img[src="path/to/image"]`
...where the path identifies the image.  I've tested this and it works beautifully.  It seems like either option would be doable.  On one hand, a class seems like a more standard way to do things; but on the other, I think there's something to be said to being able to use out-of-the-box markdown.  Thoughts?

**Comment by bryanp** [comment]
This only gives us the ability to add images, not style the callouts in other ways (e.g. add a background color to a particular type). I'd prefer to take a more semantic approach, assuming we can come up with a reasonable solution. Solving this is probably out of scope of this PR, so I'll define the work elsewhere. In the meantime, I think that we can merge this PR. Sound good to you?

**Comment by yodarunamok** [comment]
Ach, you're right.  Yep, that works.

**Pull request merged**
