### PR TITLE
Remove trailing  in request path

### PR DESCRIPTION
**Pull request by karimmtarek**
Taking care of #144.

### CODE REVIEW

**Comment by karimmtarek** [comment]
@bryanp what do you think? did I miss something?

**Comment by bryanp** [comment]
:+1: Looks good to me! You ready for me to merge? Actually, I think you have the ability to merge.

**Comment by karimmtarek** [comment]
If you are happy with it please feel free to merge it, I don't think I've access rights to merge.

**Comment by bryanp** [comment]
Thanks @karimmtarek!

**Pull request merged**
