### PR TITLE
Docker Development

### PR DESCRIPTION
**Pull request by thelastinuit**
Hi guys,

In case you like to keep your environment as clean as possible. 
I use this config to play around. Works fine so far.

### CODE REVIEW

**Comment by bryanp** [comment]
@thelastinuit Cool to see! Would this be used for developing Pakyow itself or in context of an app?

**Comment by thelastinuit** [comment]
@bryanp just for development of Pakyow, it's what I use to play around with it (and eventually contribute).
For context of an app: I'm dockerizing the Pakyow example you guys have. Later I'll PR.

**Comment by bryanp** [comment]
Thanks, @thelastinuit!

@tugboat can I get your eyes on this PR? You're more familiar with Docker than I am.

**Comment by tugboat** [comment]
@thelastinuit, this is a cool way to get around some of the issues with docker compose.  I'm not sure that this is something that we will want to put into pakyow itself though.  

It might make sense to make this into a gem or something that will set this up for you to streamline getting started developing in pakyow.  @bryanp and @thelastinuit what do you guys think?

**Comment by thelastinuit** [comment]
@tugboat Yeah, I think you're right.
My train of thought was to have a cleaner/encapsulate development environment.
I'm working on the pakyow example you have. My idea is an image ready for production. And yeah, it will depend on what gems the pakyow project have but hopefully will be easy to update.

**Comment by bryanp** [comment]
Closing this issue in favor of handling these things outside of the lib. Thanks @thelastinuit for doing the research and sharing it with us! Let us know how things end up 😃

**Pull request closed without merging**
