### PR TITLE
Issue 80

### PR DESCRIPTION
**Pull request by jphager2**
Is something simple like this what you were looking for in issue https://github.com/pakyow/pakyow/issues/80?

### CODE REVIEW

**Comment by bryanp** [comment]
Yep, that's what I was looking for in #80. I'd like to see a couple tests around this if possible.

Something else I've been thinking about since creating the issue is automatically defining restful bindings too. Currently you have to do this for the action/method to be set on a form:

```ruby
Pakyow::App.routes :post do
  restful :post, '/posts' do
    list do; end
  end
end

Pakyow::App.bindings do
  scope :post do
    restful :post
  end
end
```

It'd be nice if `:post` would be the assumed scope and the bindings were setup when using `resource`.

Thoughts?

**Comment by jphager2** [comment]
Sounds reasonable to me.

**Comment by bryanp** [comment]
This is looking really good! The `RESOURCE_ACTIONS` part took a bit to understand, but it's a clever approach. I'll be thinking about it and let you know of I think of a way to improve, but not coming up with anything right off. Anything I can help with regarding tests for the binding extension?

**Comment by jphager2** [comment]
Hey, I wrote a test similar to the test for restful routes. Could you take a look and let me know if that will cover it?

**Comment by bryanp** [comment]
The tests seem to cover it pretty well. One thing -- what's the reason for requiring `int_helper`? I'd rather avoid setting up an entire environment (which `int_helper` does) and instead require the minimal number of dependencies that we need to make this bit of functionality work properly.

**Comment by jphager2** [comment]
Sure thing. I was just being a bit lazy. I am looking at it now.

Do you know how I can get around this:
    
     Failure/Error: raise MissingTemplate, "No template named '#{name}'"
     
     Pakyow::Presenter::MissingTemplate:
       No template named 'default'

**Comment by bryanp** [comment]
Hmm, at what point is that error being raised? Mind posting the stack trace?

**Comment by jphager2** [comment]
# ./lib/presenter/view_store.rb:120:in `template_with_name'
     # ./lib/presenter/view_store.rb:190:in `block (2 levels) in load_path_info'
     # /Users/jph/projects/pakyow/pakyow/pakyow-support/lib/support/dir.rb:4:in `walk'
     # ./lib/presenter/view_store.rb:160:in `block in load_path_info'
     # ./lib/presenter/view_store.rb:159:in `each'
     # ./lib/presenter/view_store.rb:159:in `load_path_info'
     # ./lib/presenter/view_store.rb:11:in `initialize'
     # ./lib/presenter/presenter.rb:200:in `new'
     # ./lib/presenter/presenter.rb:200:in `block in load_views'
     # ./lib/presenter/presenter.rb:198:in `each_pair'
     # ./lib/presenter/presenter.rb:198:in `load_views'
     # ./lib/presenter/presenter.rb:81:in `load'
     # ./lib/presenter/presenter.rb:49:in `block in <class:Presenter>'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:408:in `instance_exec'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:408:in `block in call_stack'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:407:in `each'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:407:in `call_stack'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:424:in `load_app'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:215:in `initialize'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:35:in `new'
     # /Users/jph/projects/pakyow/pakyow/pakyow-core/lib/core/app.rb:35:in `stage'
     # ./spec/unit/app/resource_bindings_spec.rb:10:in `block (2 levels) in <top (required)>'

**Comment by bryanp** [comment]
Ah, I see. We shouldn't need the `before` hook that stages the app and creates the context.

**Comment by jphager2** [comment]
Hmm, but doesn't this get called when creating an App instance, and don't I need to work with an App instance here?

**Comment by bryanp** [comment]
Took another look after finishing my coffee, yes you're right :-)

Do you mind pushing up the code as it is when this error is raised? I think I know what's going on, but need to play with it a bit to figure out how to work around it.

**Comment by jphager2** [comment]
Sure. Just pushed.

**Comment by bryanp** [comment]
@jphager2 I pulled it down and the tests all pass for me as-is. Still hitting the exception on your end?

**Comment by jphager2** [comment]
lol, working for me too. What a nice surprise ^^.

**Comment by bryanp** [comment]
Ha, great! I haven't thought of a better way to handle `RESOURCE_ACTIONS` so I say we leave it as-is. Anything else you think this needs before I merge it in? Seems to work well!

**Comment by jphager2** [comment]
I'm okay with it.

**Comment by bryanp** [comment]
Great, thanks for your contribution!!

**Pull request merged**
